-- HERE IS THE QUERY TO DEMONSTRATE THE "ANCHORED DATATYPE" 
-- ANCHORED DATATYPE WHICH IS ASSIGN TO A VARIABLE BASED ON "DATABASE OBJECT"
-- SYNTAX {VARIABLE NAME TYPED-ATTRIBUTE%TYPE}

CREATE TABLE STUDENTS
(
    STU_ID NUMBER(2),
    STU_NAME VARCHAR2(10)
);
ALTER TABLE STUDENTS modify STU_NAME VARCHAR2(20);
/
insert into STUDENTS (STU_ID, STU_NAME) values (1,'Ethan Hunt');
insert into STUDENTS (STU_ID, STU_NAME) values (2,'Tony Montana');
/
SELECT * FROM STUDENTS;

--  START WRITING QUERY HERE
SET SERVEROUTPUT ON;
DECLARE 
    v_fname STUDENTS.STU_NAME%TYPE;
BEGIN
    SELECT STU_NAME INTO v_fname FROM STUDENTS
    WHERE STU_ID = 1;
    DBMS_OUTPUT.PUT_LINE(v_fname);
END;
/
-- DIFFERENCES
SET SERVEROUTPUT ON;
DECLARE 
    v_name varchar2(15);
BEGIN
    SELECT STU_NAME INTO v_name FROM STUDENTS
    WHERE STU_ID =1;
    DBMS_OUTPUT.PUT_LINE(v_name);
END;