-- HERE'S THE EXAMPLE OF "BIND VARIABLE/HOST VARIABLE"
-- TO DECLARE 'BIND VARIABLE' IN PL/SQL THERE'S NO REQUIREMENT OF "DECLARE" BLOCK

VARIABLE v_bind VARCHAR2(15);
EXEC :v_bind:= 'ROHIT VERMA';
-- OR INITILIZE IT EXPLECITLY

SET SERVEROUTPUT ON;
BEGIN 
    :v_bind:= 'ROHIT VERMA';
    -- PRITING IT BY USING 'DBMS_OUTPUT.PUT_LINE()'
    -- DBMS_OUTPUT.PUT_LINE(:v_bind);
END;
/
 -- PRITING IT BY USING 'PRINT' KEYWORD WHICH DON'T REQUIRE ANY PL/SQL BLOCK.
    PRINT :v_bind;
/
-- PRINTING IT BY USING 'SET AUTOPRINT ON'
SET AUTOPRINT ON;
VARIABLE v_bind VARCHAR2(20);
EXEC :v_bind:= 'Shushant Verma';