-- HERE'S THE EXAMPLE OF "DEFAULT" KEY WORD
-- DEFAULT IS THE REPLACEMENT OF ':='
-- 'NOT NULL' WILL PREVENT ASSIGNING NULL VALUE TO CONSTANT OR VARIABLE
SET SERVEROUTPUT ON;
DECLARE
    v_pi CONSTANT NUMBER(7,6)NOT NULL DEFAULT 3.141592;
BEGIN
    DBMS_OUTPUT.PUT_LINE('VALUE OF THE CONSTANT IS '||v_pi);
END;    