-- HERE'S THE DEMONSTRATION OF THE SESSION/TEMPORARY TABLE CONCEPT IN PL/SQL
-- SYNTAX:  CREATE GLOBAL TEMPORARY TABLE table_name
--          (
--              column_name column_data_type
--                  ...
--          ) ON COMMIT DELETE ROWS;

-- WRITING THE CODE FOR TEMPORARY TABLE
CREATE GLOBAL TEMPORARY TABLE emp
(
    id NUMBER(5) NOT NULL,
    name VARCHAR2(20) NOT NULL,
    city VARCHAR2(20) NOT NULL
) ON COMMIT DELETE ROWS;

-- INSERTING THE VALUES IN TABLE
INSERT INTO EMP VALUES(1, 'Test1', 'city1');
INSERT INTO EMP VALUES(2, 'Test2', 'city2');
INSERT INTO EMP VALUES(3, 'Test3', 'city3');

SELECT * FROM EMP;

-- IF YOU'LL COMMIT THEN ALL THE RECORDS WILL BE WIPEED OUT
COMMIT;