-- HERE'S THE DEMONSTRATIONS OF "DML TRIGGERS"
-- SYNTAX:      CREATE [OR REPLACE] TRIGGER trigger_name
--              {BEFORE|AFTER} trigger_event ON table_name
--              [FOR EACH ROW] [FOLLOWS another_trigger_name]
--              [ENABLE|DISABLE] WHEN condition
--              DECLARE
--                  declare statements
--              BEGIN
--                  executable statements
--              END;

-- TO UNDERSTAND THE CONCEPT OF TRIGGER FIRST CREATE A TABLE
CREATE TABLE superheros
(
    sh_name VARCHAR2(20)
);
/
-- TRIGGER CODE START FROM HERE
-- THE TABLE WHICH WILL PRINT A USER DEFINE MESSAGE EVERY TIME WHEN USER INSERT A ROW IN A TABLE

SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER bi_superheros
BEFORE INSERT ON superheros 
FOR EACH ROW 
ENABLE
DECLARE
    v_user VARCHAR2(20);
BEGIN
    SELECT user INTO v_user FROM dual;
    DBMS_OUTPUT.PUT_LINE('You just inserter a line Mr. '||v_user);
END;
/
-- FIRST EXECUTE THE ABOVE CODE THEN EXECUTE THE BELOW INSERT STATEMENT 
-- THIS OPERATION WILL GIVE SOME MESSAGE
INSERT INTO SUPERHEROS VALUES('Ironman');
-- CHECK WEATHER THE ROW IS INSERTED OR NOT 
SELECT * FROM SUPERHEROS;
/
-- FOR UPDATE THE RECORDS FROM THE TABLE
SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER bu_superheros
BEFORE UPDATE ON superheros 
FOR EACH ROW 
ENABLE
DECLARE
    v_user VARCHAR2(20);
BEGIN
    SELECT user INTO v_user FROM dual;
    DBMS_OUTPUT.PUT_LINE('just updated a line by Mr. '||v_user);
END;
/
-- FIRST EXECUTE THE ABOVE CODE THEN EXECUTE THE BELOW UPDATE STATEMENT
UPDATE SUPERHEROS SET SH_NAME = 'batman' WHERE SH_NAME = 'Superman';
-- CHECK WEATHER THE ROW IS INSERTED OR NOT 
SELECT * FROM SUPERHEROS;
/

-- COMBINATION ONE WHERE INSTERT UPDATE AND DELETE STATEMENTS WILL COMENS IN DML TRIGGER
CREATE OR REPLACE TRIGGER tr_superheros
BEFORE INSERT OR DELETE OR UPDATE ON superheros
FOR EACH ROW 
ENABLE 
DECLARE
    v_user VARCHAR2(20);
BEGIN
    SELECT user INTO v_user FROM dual;
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('One row is inserted by:'||v_user);
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('One row is deleted by:'||v_user);
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('One row is updated by:'||v_user);
    END IF;
END;
/
-- EXECUTE THE ABOVE BLOCK OF CODE THEN EXECUTE BELOW STATEMENTS ONE BY ONE TO SEE THE RESULT
INSERT INTO superheros VALUES('Antman');
SELECT * FROM SUPERHEROS;
/
UPDATE superheros SET SH_NAME = 'Spiderman' WHERE SH_NAME = 'Antman';
SELECT * FROM SUPERHEROS;
/
DELETE FROM superheros WHERE SH_NAME = 'Spiderman';
SELECT * FROM SUPERHEROS;
/































